jetArray = [];
publicVariable "jetArray";
jetCount = "jetCNT" call BIS_fnc_getParamValue;
publicVariable "jetCount";
heliCount = "heliCNT" call BIS_fnc_getParamValue;
publicVariable "heliCount";	
heliArray = [];
publicVariable "heliArray";
jetSleepTimer = "JetFreq" call BIS_fnc_getParamValue;
publicVariable "jetSleepTimer";
heliSleepTimer = "HeliFreq" call BIS_fnc_getParamValue;
publicVariable "heliSleepTimer";
waveNum = 1;
publicVariable "waveNum";
waveClear = true;
publicVariable "waveClear";
aaCount = "aaCNT" call BIS_fnc_getParamValue;
publicVariable "aaCount";
tspCount = "tspCNT" call BIS_fnc_getParamValue;
publicVariable "tspCount";
mrapCount = "mrapCNT" call BIS_fnc_getParamValue;
publicVariable "mrapCount";
apcCount = "apcCNT" call BIS_fnc_getParamValue;
publicVariable "apcCount";
tankCount = "tankCNT" call BIS_fnc_getParamValue;
publicVariable "tankCount";
aaSquad = "aaSqd" call BIS_fnc_getParamValue;
publicVariable "aaSquad";
infArray = [];
publicVariable "infArray";
guardArray = [];
publicVariable "guardArray";
aaArray = [];
publicVariable "aaArray";
tsArray = [];
publicVariable "tsArray";
mrapArray = [];
publicVariable "mrapArray";
apcArray = [];
publicVariable "apcArray";
tankArray = [];
publicVariable "tankArray";
trg = 0;
publicVariable "trg";
aoLocation = [];
publicVariable "aoLocation";
eSide = EAST;
publicVariable "eSide";